# .github/workflows/ip_validation.yml

name: IP Validation

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  schedule:
    - cron: '0 2 * * *'   # 每天凌晨2点触发一次

jobs:
  validate-ips:
    runs-on: ubuntu-latest

    steps:
      # 步骤1：检出仓库内容
      - name: Checkout repository
        uses: actions/checkout@v3

      # 步骤2：设置Python环境
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 步骤3：缓存pip依赖
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 步骤4：升级pip并安装依赖
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 步骤5：运行Python脚本
      - name: Run IP Validation Script
        run: |
          python iptest.py
        env:
          PYTHONWARNINGS: "ignore:Unverified HTTPS request"

      # 步骤6：上传日志和输出文件作为构件（Artifacts）
      - name: Upload Logs and Outputs
        uses: actions/upload-artifact@v3
        with:
          name: ip-validation-results
          path: |
            iptest.log
            itv-ip.txt
            fail.txt
            true.txt
            1.txt

      # 步骤7：将生成的文件提交回仓库（可选）
      - name: Commit and Push Changes
        if: success()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add iptest.log itv-ip.txt fail.txt true.txt 1.txt
          git commit -m "Update IP validation results [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
