# .github/workflows/ip_validation.yml

name: IP Validation

on:
  workflow_dispatch:   # 仅允许手动触发

jobs:
  validate-ips:
    runs-on: ubuntu-latest

    steps:
      # 步骤1：检出仓库内容
      - name: Checkout repository
        uses: actions/checkout@v3

      # 步骤2：设置Python环境
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 步骤3：升级pip并安装依赖
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install requests dnspython

      # 步骤4：运行Python脚本
      - name: Run IP Validation Script
        run: |
          python iptest.py
        env:
          PYTHONWARNINGS: "ignore:Unverified HTTPS request"

      # 步骤5：上传日志和输出文件作为构件（Artifacts）
      - name: Upload Logs and Outputs
        uses: actions/upload-artifact@v3
        with:
          name: ip-validation-results
          path: |
            iptest.log
            itv-ip.txt
            fail.txt
            true.txt
            1.txt
